name: go-test

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  go-test:
    uses: blinklabs-io/actions/.github/workflows/reuseable-go-test.yml@main
    with:
      go-versions: '["1.25.x"]'
      platforms: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      pre-test-command: make build
      test-flags: -v -race -timeout 10m
